---
title: "Imaging mass cytometry reveals tumor and immune spatial and phenotypic clusters associated with clinical outcomes in diffuse large B cell lymphoma (DLBCL)"
author: "Anthony Colombo+,Monirath Hav+, Erik Gerdtsson"
date: "`r Sys.Date()`"
output: html_document
---


# {.tabset}  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup {.tabset}


### Helper Functions
```{r, eval=FALSE}

  grabNearest5<-function(types,from=NULL,to=NULL){
  nnd<-cbind(nncross(types[[from]],types[[to]],k=1),
	nncross(types[[from]],types[[to]],k=2),
	nncross(types[[from]],types[[to]],k=3),
	nncross(types[[from]],types[[to]],k=4),
	nncross(types[[from]],types[[to]],k=5))
     ids<-nnd[,grepl("which",colnames(nnd))]
  centroid<-data.frame(t(apply(ids,1,function(x) colMeans(coords(types[[to]])[as.numeric(x),]))))
  coor<-coords(types[[from]])
  p = data.frame(cent.dist=sqrt( (coor$x-centroid$x)^2+ (coor$y-centroid$y)^2))
 return(p)
 }



##Vito Zanotelli algorithm for spatial.
makePermutationNBHD<-function(dat_cells=NULL,dat_relation=NULL,n_perm=100){
  d = prepare_tables(dat_cells, dat_relation)
  dat_baseline = apply_labels(d[[1]], d[[2]]) %>%
  aggregate_histo()


 set.seed(12312)
   dat_perm = rbindlist(mclapply(1:n_perm, function(x){
  dat_labels = shuffle_labels(d[[1]])
  apply_labels(dat_labels, d[[2]]) %>%
    aggregate_histo()
  },mc.cores = 1
  ), idcol = 'run') 
 
   dat_p <- calc_p_vals(dat_baseline, dat_perm, n_perm = n_perm, p_tresh = 0.05) 
 ### plotting heatmap.
  
   pmat = dcast(dat_p, 'FirstLabel ~ SecondLabel', value.var = 'sigval', fun.aggregate = sum,
             fill=0, drop=F)
   rname = pmat$FirstLabel
   pmat<-as.data.table(pmat)
   pmat = pmat[,which(colnames(pmat)!="FirstLabel"),with=FALSE] %>%
    as.matrix()
row.names(pmat) <- rname
 ### he structures his probabilities greater than and less than.
  return(list(pmat=pmat,dat_p=dat_p))
 }


 ##Vito Zanotelli relation tables.
 createRelationTable<-function(dn5=NULL,myPheno=NULL,minDistance=12){
  ##for each ROI, create PPP
  dat_relation2<-c()
  for(roi in unique(dn5$ROIID)){
   message(roi)
   dats<-subset(dn5,dn5$ROIID==roi)
   synth3.cells<-phenographToPPP(case=dats,marks=factor(dats[,myPheno]))
   dat_relation<-findSecondObjectNumber(pp=synth3.cells,minDistance=minDistance)
  dat_relation$Relationship<-"Neighbors"
  dat_relation[,"First Object Name"]<-"cell"
  dat_relation[,"First Image Number"]<-roi
  dat_relation[,"Second Object Name"]<-"cell"
  dat_relation[,"Second Image Number"]<-roi
  dat_relation2<-rbind(dat_relation2,dat_relation)
  }
 return(data.table(dat_relation2))
}
 #### borrowing from Vito's pipeline.
  findSecondObjectNumber<-function(pp=NULL,minDistance=13.5){
  ##FIX ME : use apply nbhd
   x<-pairdist(pp)
    id<-apply(x,1,function(x) which(x<=minDistance))
  ##stack the list into long format
  names(id)<-as.character(seq(1,npoints(pp)))
  datRel<-stack(id)
 ##the second object near the first fixed object.
  colnames(datRel)<-c("Second Object Number","First Object Number")
   ##exclude self
   datRel<-datRel[which(datRel[,"First Object Number"]!=datRel[,"Second Object Number"]),]
   datRel[,1]<-as.numeric(datRel[,1])
  datRel[,2]<-as.numeric(datRel[,2])
   return(datRel)
  }


 phenographToPPP<-function(case=NULL,marksCase=NULL,shift=FALSE){
 suppressPackageStartupMessages( require(spatstat))
  ##case: the case is the phenographed CSV 
  ##returns the PPP object, with marks as the original data frame.
  ##note that the window minimum is set to 0. This **SHOULD** not hopefully interfere with the spatial coordinates.
 ##this change of min 0 was necessary for clusterset function which conflicted with the window range.
  if(shift==TRUE){
  minX<-min(case[,"X_position"])
  minY<-min(case[,"Y_position"])
 case[,"X_position"]<-case[,"X_position"]-minX
 case[,"Y_position"]<-case[,"Y_position"]-minY
    mypat<-ppp(case[,"X_position"],case[,"Y_position"],c(min(case[,"X_position"]),summary(case[,"X_position"])[6]),c(min(case[,"Y_position"]),summary(case[,"Y_position"])[6]),marks=marksCase)
  ##shifting via spatstat causes non-stationary errors. FIXME: use manual shifting of coordinates prior   
 #mypat<-spatstat::shift(mypat,c(-minX,-minY))
  }else{
    #mypat<-ppp(case[,"X_position"],case[,"Y_position"],c(0,summary(case[,"X_position"])[6]),c(0,summary(case[,"Y_position"])[6]),marks=marksCase)
 mypat<-ppp(case[,"X_position"],case[,"Y_position"],c(min(case[,"X_position"]),max(case[,"X_position"])),c(min(case[,"Y_position"]),max(case[,"Y_position"])),marks=marksCase) 
 } 

 ## scale in  micrometers
   unitname(mypat)<-"micrometer"

  return(mypat)
 }

 ###Vito helper
 plotVito<-function(synth=NULL,minDistance=1){
 
 zz<-data.frame(ROIID="synth2",unsup.interface=marks(synth),CellId=seq(1,npoints(synth)),
	X_position=coords(synth)[,"x"],
	Y_position=coords(synth)[,"y"])

 dat_cells<-data.frame(ImageNumber=zz$ROIID,
	ObjectNumber=zz$CellId,
	label=as.character(zz$unsup.interface),
	group=zz$ROIID)
  dat_cells<-data.table(dat_cells)
  dat_relation_15<-createRelationTable(dn5=zz,myPheno="unsup.interface",minDistance=minDistance)
  p1<-makePermutationNBHD(dat_cells=dat_cells,dat_relation=dat_relation_15,n_perm=1000)


 ### he structures his probabilities greater than and less than.
  pmat<-p1$pmat
  library(pheatmap)
  cols = rev(brewer.pal(11,'Spectral'))
  cmap = colorRampPalette(cols)
  hr <- hclust(dist(pmat), method="ward.D")
   pheatmap(pmat,color=(cmap(3)),  
    cluster_cols = TRUE, 
	cluster_rows = TRUE, 
    labels_col = colnames(pmat), labels_row = rownames(pmat), 
    display_numbers = TRUE, number_color = "black", 
    fontsize = 12, fontsize_number = 12,main="Touching significance test")
 }


 getPhenoColors<-function(full.dn4){
 require(circlize)
  tsn<-full.dn4[which(!is.na(full.dn4$tSNE1) & !is.na(full.dn4$tSNE2)),c("tSNE1",
	"tSNE2",
	"Cell_CD20",
	"Cell_CD3",
	"Cell_CD4",
	"Cell_CD31",
	"Cell_CD4",
	"Cell_CD68",
	"Cell_CD8",
	"Cell_FOXP3",
	"Cell_BCL2",
	"uniqueLabel","response","ROIID",
	"unsup.subcommunity")]
  ##balanced response representation.
   table(tsn$response)
  tsn$primary.phenotype<-as.character(tsn$unsup.subcommunity)
 tsn$primary.phenotype<-factor(tsn$primary.phenotype)
   cd8s<-colorRampPalette(c("darkseagreen","green"),20)
  cd4s<-colorRampPalette(c("lightsteelblue1","blue"),20)
  macs<-colorRampPalette(c("magenta","maroon4"),20)
   tregs<-colorRampPalette(c("plum2","purple"),20)
   tumrs<-colorRampPalette(c("grey24","grey64"),20)
   phenoColors<-c(cd4s(14)[seq(1,14,2)],
	cd8s(14)[seq(1,14,2)],"red",macs(12)[seq(1,12,2)],tregs(12)[seq(1,12,2)],tumrs(10))

 names(phenoColors)<-levels(factor(tsn$primary.phenotype))
   ##manual color change code.
   phenoColors["Macrophage_2"]<-"darkblue"
   phenoColors["Macrophage_5"]<-"yellow"
   phenoColors["CD8_7"]<-"black"

   return(phenoColors)
 }

  getSpatialPhenoColors<-function(full.dn4=NULL){
	##this uses the color coding from the Tumor spatial classification
  phenoColors<-phenoColors<-getPhenoColors(full.dn4)

   cols<-data.frame(phenotype= unique(full.dn4.5nn2$tumor.5nn.class.unsup),
	colors="black",
	stringsAsFactors=FALSE)
   for(i in 1:nrow(cols)){
   id<-which(names(phenoColors)[i]==cols$phenotype)
   cols$colors[id]<-phenoColors[i]
  }
        
 	cols[which(cols$phenotype=="Tumor_b"),"colors"]<-"lightslategrey"
     cols[which(cols$phenotype=="Tumor_g"),"colors"]<-"gray89"
       cols[which(cols$phenotype=="Tumor_c"),"colors"]<-"black"
 	 cols[which(cols$phenotype=="Tumor_f"),"colors"]<-"khaki1"
   cols[which(cols$phenotype=="Tumor_i"),"colors"]<-"tan3"
 ###REF
	       cols[which(cols$phenotype=="Tumor_e"),"colors"]<-"orange"
 	       cols[which(cols$phenotype=="Tumor_a"),"colors"]<-"cyan"
  	       cols[which(cols$phenotype=="Tumor_h"),"colors"]<-"lightpink"

    	cols[which(cols$phenotype=="Tumor_d"),"colors"]<-color_clusters[6]


   return(cols)
 }






 grabROIDistanceRange<-function(synth=NULL,uniqueLabel=NULL,k=1){
  ## create ppp
  nnd<-as.data.frame(nndist(synth,k=k,by=marks(synth)))
  colnames(nnd)<-paste0("k_",k,"_",colnames(nnd))
  for(i in 1:ncol(nnd)){
  nnd[which(is.infinite(nnd[,i])),i] <-300
 }##
   nnd$marks<-marks(synth)
   nnd$K=1
   nnd$uniqueLabel<-uniqueLabel 
  return(nnd)
  }

  distanceClusterROI.5NN<-function(synth=NULL,zz=NULL){
  require(Rphenograph)
  nnd1<-grabDistanceRange(synth,uniqueLabel=zz$uniqueLabel,k=1)
    nnd2<-grabDistanceRange(synth,uniqueLabel=zz$uniqueLabel,k=2)
  nnd3<-grabDistanceRange(synth,uniqueLabel=zz$uniqueLabel,k=3)
  nnd4<-grabDistanceRange(synth,uniqueLabel=zz$uniqueLabel,k=4)
  nnd5<-grabDistanceRange(synth,uniqueLabel=zz$uniqueLabel,k=5)
  ## need to average them.
 
  ## assemble
  nnd<-cbind(nnd1[,grepl("k_",colnames(nnd1))],
	nnd2[,grepl("k_",colnames(nnd2))],
	nnd3[,grepl("k_",colnames(nnd3))],
	nnd4[,grepl("k_",colnames(nnd4))],
	nnd5[,grepl("k_",colnames(nnd5))])
	#nnd9[,1:3],
	#nnd10[,1:3])
   nndImmune<-rowMeans(nnd[,grepl("_immune",colnames(nnd))])
   nndTumor<-rowMeans(nnd[,grepl("_Tumor",colnames(nnd))])
   nnd.ti<-data.frame(nndImmune,nndTumor)
  ###use the 5NN distances to immune and tumor.
    pheno<-Rphenograph(nnd.ti,k=40)
 ##########
    nnd$cluster<-factor(membership(pheno[[2]]))
     nnd$uniqueLabel<-zz$uniqueLabel
     nnd$marks<-marks(synth)
   stopifnot(all(nrow(nnd)==nrow(zz)))
   zz$tumor.immune.5nn<-nnd$cluster
 zz$nndImmune.5nn<-nnd.ti$nndImmune
 zz$nndTumor.5nn<-nnd.ti$nndTumor
  return(zz)
}


 ## phenograph to spatial point patter (PPP) object
 phenographToPPP<-function(case=NULL,marksCase=NULL,shift=FALSE){
 suppressPackageStartupMessages( require(spatstat))
  ##case: the case is the phenographed CSV 
  ##returns the PPP object, with marks as the original data frame.
  ##note that the window minimum is set to 0. This **SHOULD** not hopefully interfere with the spatial coordinates.
 ##this change of min 0 was necessary for clusterset function which conflicted with the window range.
  if(shift==TRUE){
  minX<-min(case[,"X_position"])
  minY<-min(case[,"Y_position"])
 case[,"X_position"]<-case[,"X_position"]-minX
 case[,"Y_position"]<-case[,"Y_position"]-minY
    mypat<-ppp(case[,"X_position"],case[,"Y_position"],c(min(case[,"X_position"]),summary(case[,"X_position"])[6]),c(min(case[,"Y_position"]),summary(case[,"Y_position"])[6]),marks=marksCase)
  ##shifting via spatstat causes non-stationary errors. FIXME: use manual shifting of coordinates prior   
 #mypat<-spatstat::shift(mypat,c(-minX,-minY))
  }else{
    #mypat<-ppp(case[,"X_position"],case[,"Y_position"],c(0,summary(case[,"X_position"])[6]),c(0,summary(case[,"Y_position"])[6]),marks=marksCase)
 mypat<-ppp(case[,"X_position"],case[,"Y_position"],c(min(case[,"X_position"]),max(case[,"X_position"])),c(min(case[,"Y_position"]),max(case[,"Y_position"])),marks=marksCase) 
 } 

 ## scale in  micrometers
   unitname(mypat)<-"micrometer"

  return(mypat)
 }

 getSpatialPhenoColors<-function(full.dn4=NULL){
	##this uses the color coding from the Tumor spatial classification
  phenoColors<-phenoColors<-getPhenoColors(full.dn4)

   cols<-data.frame(phenotype= unique(full.dn4.5nn2$tumor.5nn.class.unsup),
	colors="black",
	stringsAsFactors=FALSE)
   for(i in 1:nrow(cols)){
   id<-which(names(phenoColors)[i]==cols$phenotype)
   cols$colors[id]<-phenoColors[i]
  }
        
 	cols[which(cols$phenotype=="Tumor_b"),"colors"]<-"lightslategrey"
     cols[which(cols$phenotype=="Tumor_g"),"colors"]<-"gray89"
       cols[which(cols$phenotype=="Tumor_c"),"colors"]<-"black"
 	 cols[which(cols$phenotype=="Tumor_f"),"colors"]<-"khaki1"
   cols[which(cols$phenotype=="Tumor_i"),"colors"]<-"tan3"
 ###REF
	       cols[which(cols$phenotype=="Tumor_e"),"colors"]<-"orange"
 	       cols[which(cols$phenotype=="Tumor_a"),"colors"]<-"cyan"
  	       cols[which(cols$phenotype=="Tumor_h"),"colors"]<-"lightpink"

    	cols[which(cols$phenotype=="Tumor_d"),"colors"]<-color_clusters[6]


   return(cols)
 }


## phenograph to spatial point patter (PPP) object
 phenographToPPP<-function(case=NULL,marksCase=NULL,shift=FALSE){
 suppressPackageStartupMessages( require(spatstat))
  ##case: the case is the phenographed CSV 
  ##returns the PPP object, with marks as the original data frame.
  ##note that the window minimum is set to 0. This **SHOULD** not hopefully interfere with the spatial coordinates.
 ##this change of min 0 was necessary for clusterset function which conflicted with the window range.
  if(shift==TRUE){
  minX<-min(case[,"X_position"])
  minY<-min(case[,"Y_position"])
 case[,"X_position"]<-case[,"X_position"]-minX
 case[,"Y_position"]<-case[,"Y_position"]-minY
    mypat<-ppp(case[,"X_position"],case[,"Y_position"],c(min(case[,"X_position"]),summary(case[,"X_position"])[6]),c(min(case[,"Y_position"]),summary(case[,"Y_position"])[6]),marks=marksCase)
  ##shifting via spatstat causes non-stationary errors. FIXME: use manual shifting of coordinates prior   
 #mypat<-spatstat::shift(mypat,c(-minX,-minY))
  }else{
    #mypat<-ppp(case[,"X_position"],case[,"Y_position"],c(0,summary(case[,"X_position"])[6]),c(0,summary(case[,"Y_position"])[6]),marks=marksCase)
 mypat<-ppp(case[,"X_position"],case[,"Y_position"],c(min(case[,"X_position"]),max(case[,"X_position"])),c(min(case[,"Y_position"]),max(case[,"Y_position"])),marks=marksCase) 
 } 

 ## scale in  micrometers
   unitname(mypat)<-"micrometer"

  return(mypat)
 }


zScorePatientExpression<-function(full.dn4=NULL,markers=NULL,ROIID.column=NULL){
  X3<-full.dn4[,c(markers,ROIID.column)]%>%group_by(ROIID)%>%summarise_all(funs(sd))%>%data.frame
  X2<-full.dn4[,c(markers,ROIID.column)]%>%group_by(ROIID)%>%summarise_all(funs(mean))%>%data.frame
   ###
   z<-full.dn4
  for(cl in unique(full.dn4$ROIID)){
   for(mark in colnames(X2)[-1]){
  z[which(z$ROIID==cl),which(colnames(z)==mark)]<- ( z[which(z$ROIID==cl),which(colnames(z)==mark)]-X2[which(X2$ROIID==cl),which(colnames(X2)==mark)])/(X3[which(X3$ROIID==cl),which(colnames(X3)==mark)])
   }
 }
 return(z)
 }


compareRandomNetwork<-function(full.dn4=NULL,N=100,myFormula=formula("NGCB~Tumor_a")
){
   randomDomain<-list() 
  for(j in 1:N){
 message(j)
  x<-full.dn4$tumor.5nn.class.unsup
  x2<-data.frame(uniqueLabel=full.dn4$uniqueLabel,
	tumor.5nn.random=sample(x,replace=F))
  randomDomain[[length(randomDomain)+1]]<-x2
  }
   rands<-full.dn4
   mlr<-list()
   for(i in 1:length(randomDomain)){
  message(i)
    rands$tumor.5nn.class.unsup<-randomDomain[[i]][match(rands$uniqueLabel,randomDomain[[i]]$uniqueLabel),"tumor.5nn.random"]
    tum<-as.data.frame.matrix(table(rands$case,rands$tumor.5nn.class.unsup))
  tum<-tum/rowSums(tum)
  tum<-as.data.frame(tum[,grepl("Tumor_",colnames(tum))])
  tum$case<-rownames(tum)
  imm<-tum
  imm$IPI<-rands$IPI[match(imm$case,rands$case)]
  imm$NGCB<-rands$COO[match(imm$case,rands$case)]
  imm$NGCB<-ifelse(imm$NGCB=="NGCB",1,0)
  imm<-imm[,which(colnames(imm)!="case")]


  ## HANS OR
  rand.mlr<- glm(myFormula,family='binomial',imm)%>%summary
  mlr[[(length(mlr)+1)]]<-rand.mlr
  }## loop

 return(mlr)
 }


```


### Synthetic validation
```{r, eval=FALSE}
 library(data.table)
library(dplyr)
library(magrittr)
library(dtplyr)
library(ggplot2)
library(parallel)
library(neighbouRhood)
library(gplots)
library(RColorBrewer)
library(spatstat)
  library(Rphenograph)

  library(recmap)
 checkerboard8x8 <- checkerboard(12)
  
  #unmarked synth
  synth<-ppp(checkerboard8x8[,"x"],
	checkerboard8x8[,"y"],
	c(0,max(checkerboard8x8[,"x"])+1),c(-1,max(checkerboard8x8[,"y"]))+1)
  a<-rep(c(0,1),6)
  b<-rep(c(2,0),6)
  marks(synth)<-factor(rep(c(a,b),6))


  ## create synthetic neighborhoods.
   ##spatially regular
    cells<-discs(synth,radii=0.5)
  synth<-ppp(checkerboard8x8[,"x"],
	checkerboard8x8[,"y"],
	 cells)

  marks(synth)<-factor(rep(c(a,b),6))
   synth_original<-synth
 ## 5-NN

  #savePlot(file="~/Documents/imageAnalysis/DLBCL/simpleModel-1-14/Figure6-CD8-5NN-spatialModel-RICO/synthetic-5nn-validations/synthetic1/synthetic.distance.classification.png")

 ## use Vito's algorithm to evaluate.
 zz<-data.frame(ROIID="synth1",unsup.interface=marks(synth),CellId=seq(1,npoints(synth)),
	X_position=coords(synth)[,"x"],
	Y_position=coords(synth)[,"y"])

 dat_cells<-data.frame(ImageNumber=zz$ROIID,
	ObjectNumber=zz$CellId,
	label=as.character(zz$unsup.interface),
	group=zz$ROIID)
  dat_cells<-data.table(dat_cells)
  dat_relation_15<-createRelationTable(dn5=zz,myPheno="unsup.interface",minDistance=1)
  p1<-makePermutationNBHD(dat_cells=dat_cells,dat_relation=dat_relation_15,n_perm=1000)

  pmat<-p1$pmat
  library(pheatmap)
  cols = rev(brewer.pal(11,'Spectral'))
  cmap = colorRampPalette(cols)
  hr <- hclust(dist(pmat), method="ward.D")
   pheatmap(pmat,color=(cmap(3)),  
    cluster_cols = TRUE, 
	cluster_rows = TRUE, 
    labels_col = colnames(pmat), labels_row = rownames(pmat), 
    display_numbers = TRUE, number_color = "black", 
    fontsize = 12, fontsize_number = 12,main="Touching significance test")


################################################
   ## synthetic image 2.
   synth2<-ppp(checkerboard8x8[,"x"],
	checkerboard8x8[,"y"],
	c(0,max(checkerboard8x8[,"x"])+1),c(-1,max(checkerboard8x8[,"y"]))+1)

  a<-c(2,rep(1,4),rep(2,7))
  b<-rep(2,12)
  marks<-(c(b,rep(a,4),rep(b,7)))
  marks[which(marks(synth)=="0")]<-"0"
  marks(synth2)<-factor(marks)

  
  cells<-discs(synth2,radii=0.5)
 synth2.cells<-ppp(checkerboard8x8[,"x"],
	checkerboard8x8[,"y"],
	 cells)
 marks(synth2.cells)<-factor(marks)
  par(mfrow=c(1,1))
 plot(synth2.cells,cols=c("green","purple","blue"),main="Synthetic pattern 2")


 ## 5-NN distance clustering for cluster 1.
   ## perform distance clustering.
 types<-split(synth2.cells)
  dat<- data.frame(to1=grabNearest5(types,from="1",to="2"),to2=grabNearest5(types,from="1",to="1"))
  pheno<-Rphenograph(dat,k=5)
      dat$phenograph_cluster<- factor(membership(pheno[[2]]))
   synth2.cells2<-synth2.cells
  marks(synth2.cells2)<-as.character(marks(synth2.cells2))
   marks(synth2.cells2)[which(marks(synth2.cells)=="1")]<-paste0("1_",dat$phenograph_cluster)
  marks(synth2.cells2)<-factor(marks(synth2.cells2))
 par(mfrow=c(1,2))
 plot(synth2.cells,cols=c("black","purple","blue"),main="Synthetic pattern 2")
  plot(synth2.cells2,cols=c("black","mediumpurple4","mediumorchid3","blue"),pch=c(1,17,17,3),main="Synthetic distance classification")
  #  savePlot(file="~/Documents/imageAnalysis/DLBCL/simpleModel-1-14/Figure6-CD8-5NN-spatialModel-RICO/synthetic-5nn-validations/synthetic2/synthetic.pattern2.classification.clustering.png")

 ## Vito's analysis on synthetic 2
 ## use Vito's algorithm to evaluate.
 
 
  plotVito(synth=synth2.cells2)
   # savePlot(file="synthetic2.5nndistance.png")



 ### Synthetic image  3
 synth3<-ppp(checkerboard8x8[,"x"],
	checkerboard8x8[,"y"],
	c(0,max(checkerboard8x8[,"x"])+1),c(-1,max(checkerboard8x8[,"y"]))+1)

  a<-c(rep("A",4),rep("B",4),rep("C",2),rep("D",2))
  b<-c(rep("C",9),rep("D",3))
  c<-rep("D",12)
  marks3<-c(b,rep(a,4),rep(b,5),rep(c,2))
  marks3[which(marks=="0")]<-"E"
  marks(synth3)<-factor(marks3)

  
  cells<-discs(synth3,radii=0.5)
 synth3.cells<-ppp(checkerboard8x8[,"x"],
	checkerboard8x8[,"y"],
	 cells)
 marks(synth3.cells)<-factor(marks3)
 par(mfrow=c(1,2))
 plot(synth3.cells,cols=c("red","blue","purple","green","black"),main="Synthetic pattern 3")


 ## distance clustering.
  ## perform distance clustering.
 types<-split(synth3.cells)
  dat<- data.frame(to1=grabNearest5(types,from="A",to="B"),
	to2=grabNearest5(types,from="A",to="A"),
	to3=grabNearest5(types,from="A",to="C"),
	to4=grabNearest5(types,from="A",to="D"))
	
  pheno<-Rphenograph(dat,k=5)
      dat$phenograph_cluster<- factor(membership(pheno[[2]]))
   synth4<-synth3.cells
   marks(synth4)<-as.character(marks(synth4))
   marks(synth4)[which(marks(synth4)=="A")]<-paste0("A_",dat$phenograph_cluster)
  marks(synth4)<-factor(marks(synth4))
 plot(synth4,cols=c("red","cyan","blue","purple","green","black"),pch=c(1,1,2,3,4,5),main="Synthetic distance classification")
          # savePlot(file="synthetic.pattern3.classification.png")

  dev.new();par(mfrow=c(1,2))
 plotVito(synth=synth4,minDistance=1)
  #  savePlot(file="synthetic3.5nndistance.1.minDistance.png")
 plotVito(synth=synth4,minDistance=1.6)
  #  savePlot(file="~/Documents/imageAnalysis/DLBCL/simpleModel-1-14/Figure6-CD8-5NN-spatialModel-RICO/synthetic-5nn-validations/synthetic3/synthetic3.5nndistance.1.6.minDistance.png")


 ## synthetic 4
  ### Diffuse synthetics.  
  ### tumor/immune interface.
   synth5<-ppp(checkerboard8x8[,"x"],
	checkerboard8x8[,"y"],
	c(0,max(checkerboard8x8[,"x"])+1),c(-1,max(checkerboard8x8[,"y"]))+1)

  a<-rep("A",12)
  b<-rep("B",12)
  
  marks5<-c(rep(a,6),rep(b,6))
  marks(synth5)<-factor(marks5)
  
  
  cells<-discs(synth5,radii=0.5)
 synth5.cells<-ppp(checkerboard8x8[,"x"],
	checkerboard8x8[,"y"],
	 cells)
 marks(synth5.cells)<-factor(marks5)
 synth5_2<-synth5.cells
  par(mfrow=c(1,1))
 plot(synth5.cells,cols=c("red","blue"),main="Synthetic pattern 5")
   types<-split(synth5.cells)
  dat<- data.frame(to1=grabNearest5(types,from="A",to="B"))
	  pheno<-Rphenograph(dat,k=15)
      dat$phenograph_cluster<- factor(membership(pheno[[2]]))

   marks(synth5_2)<-as.character(marks(synth5.cells))
   marks(synth5_2)[which(marks(synth5_2)=="A")]<-paste0("A_",dat$phenograph_cluster)
  marks(synth5_2)<-factor(marks(synth5_2))
 par(mfrow=c(1,2))
  plot(synth5.cells,cols=c("red","blue"),main="Synthetic pattern 5")
 plot(synth5_2,cols=c("red","cyan","purple","green","orange","black","blue"),pch=c(1,1,1,1,1,1,2),main="Synthetic distance classification")
     # savePlot(file="synthetic.pattern4.classification.png")

 plotVito(synth=synth5_2,minDistance=1)
   # savePlot(file="synthetic4.5nndistance.1.minDistance.png")
 
  plotVito(synth=synth5_2,minDistance=1.6)
  #  savePlot(file="synthetic4.5nndistance.1.6.minDistance.png")


```


### Lymph node classification
```{r, eval=FALSE}

 ## spatial analysis on normal lymphnode.
  ## validate on the single Steidl Lymph-node.
   load("~/Documents/imageAnalysis/DLBCL/monirath/myData/revision-comments-11-6/survival-analysis-morphological-variants/PDL1-neighborhood-analysis/workingDir/steidl-lymphode-classification/steidl-RLN-classification-analysis-Case4-1-23/rln.dn4.nbhd.5nn.1-23.RData")

  case4<-subset(rln.nbhd.5nn,rln.nbhd.5nn$ROIID=="Case4_9")
  case4$annotated[which(case4$primary.phenotype=="TFH")]<-"CD4"
   case4.ppp<-phenographToPPP(case=case4,marks=factor(case4$primary.phenotype))
  case4.ppp2<-phenographToPPP(case=case4,marks=factor(case4$annotated))
  par(mfrow=c(2,2))
  plot(split(case4.ppp2)["BCell"],main="BCell")
   plot(split(case4.ppp2)["CD4"],main="CD4")
    plot(split(case4.ppp)["TFH"],main="TFH")

 ### classify Bcells distance to all other cells.
 ## use the 5NN classification.

  load("~/Documents/imageAnalysis/steidl/shape-objects-2-4/Case4_9_spdf-1-23.validation.RData")
  spdf$cellType2<-as.character(spdf$cellType)  
  rln<-rln.nbhd.5nn
   spdf$uniqueLabel<-spdf$id
  spdf2<-left_join(spdf,rln[which(rln$ROIID=="Case4_9"),c("uniqueLabel","spatial.metaCluster")],by="uniqueLabel")

 ## color code the tumor core/mantle/crust in RLN.
  rln.dist<-rln.nbhd.5nn%>%group_by(spatial.metaCluster)%>%summarise(CD4=mean(th.centroid),CD8=mean(tcyt.centroid),MAC=mean(mac.centroid))%>%data.frame
  rln.dist<-rln.dist[1:7,]
  rln.dist$distance<-rln.dist[,-1]%>%rowMeans
  rln.dist<-rln.dist[-1,]
  rln.dist<-rln.dist[order(rln.dist$distance),]
  ### color code for case4_9
   load("~/Documents/imageAnalysis/DLBCL/simpleModel-1-14/Figure6-CD8-5NN-spatialModel-RICO/tumor.cd8.dlbcl/full.dn4.5nn2.CD8.MC.RData")
 ## load the interactions
  spatCol<-getSpatialPhenoColors(full.dn4.5nn2)


  spatCol<-getSpatialPhenoColors(full.dn4=full.dn4)


  spdf2$cd8.spatial<-factor(spdf2$spatial.metaCluster)
 

  spdf2<-spdf2[which(spdf2$cellType!="NK" & spdf2$cellType!="HRS"),]
  spdf2$cellType<-factor(spdf2$cellType)
 
  rln.colors<-c("CD4"="blue",
			"MAC"="magenta",
			"Endothelial"="red",
			"TREG"="purple",
			"CD8"="green",					
					"1"="gray39",
                                               "2"="tan3",
                                               "3"="#B17BA6",
                                               "4"="khaki1",
                                               "5"="black",
                                            "6"="orange",
					"7"="lightslategrey",
					"TFH"="#7BAFDE",
					"BCell"="gray39",
				        "DC"="#882E72")

 colorKey=data.frame(colors=rln.colors,row.names=names(rln.colors),stringsAsFactors=FALSE)    
	  
  spdf2$cd8.spatial<-factor(spdf2$cd8.spatial,levels=names(rln.colors))
  spdf2$cd8.spatial<-droplevels(spdf2$cd8.spatial)

  test<- ggplot(spdf2,aes(x=long,y=lat,group=id,fill=cd8.spatial)) +
      geom_polygon(size=0.1,colour="black") +scale_fill_manual(values=as.character(colorKey[match(levels(spdf2$cd8.spatial),rownames(colorKey)),'colors']))+ggtitle("Case4 5NN classification")+theme_bw()
   test
 # savePlot(file="~/Documents/imageAnalysis/DLBCL/simpleModel-1-14/Figure6-CD8-5NN-spatialModel-RICO/synthetic-5nn-validations/RLN-validation/lymphnode.case4.validation.single.png")



 spdf2$cellType<-as.character(spdf2$cellType)
 spdf2$cellType[which(spdf2$cd8.spatial=="TFH")]<-"TFH"
  spdf2$cellType<-factor(spdf2$cellType)
  test2<- ggplot(spdf2,aes(x=long,y=lat,group=id,fill=cellType)) +
      geom_polygon(size=0.1,colour="black") +scale_fill_manual(values=as.character(colorKey[levels(spdf2$cellType),"colors"]))+ggtitle("Case4")+theme_bw()
    test2
  library(gridExtra)
   grid.arrange(test,test2,ncol=2)
 # savePlot(file="lymphnode.case4.validation.png")


 ## Vito's evaluation.
  dat_cells<-data.frame(ImageNumber=rln$ROIID,
	ObjectNumber=rln$CellId,
	label=as.character(rln$spatial.metaCluster),
	group=rln$ROIID)
  dat_cells<-data.table(dat_cells)
  dat_relation_15<-createRelationTable(dn5=rln,myPheno="spatial.metaCluster",minDistance=15)
 # save(dat_relation_15,file="dat_relation_15_RLN.spatial.distance.RData")
  p1<-makePermutationNBHD(dat_cells=dat_cells,dat_relation=dat_relation_15,n_perm=1000)
 # save(p1,file="p1_15_RLN.spatial.distance.RData")
  
  cols = rev(brewer.pal(11,'Spectral'))
  cmap = colorRampPalette(cols)
 p2<-p1$pmat[!rownames(p1$pmat)%in%c("HRS","CD8.TREG","Myeloid.Granulocytes","NK"),
	!colnames(p1$pmat)%in%c("HRS","CD8.TREG","Myeloid.Granulocytes","NK")]

  hr <- hclust(dist(p2), method="ward.D")
     pheatmap(p2, 
	color = cmap(25), 
    cluster_cols = TRUE, 
    cluster_rows = TRUE, 
    labels_col = colnames(p2),
    labels_row = colnames(p2), 
    display_numbers = TRUE,  
    fontsize = 14,
    cutree_rows=2,
	cutree_cols=2)
 # savePlot(file="RLN.cohort.Bcell.interactions.1000.5NN.png")

 ##fix me adapt this method.
 id<-which(rln$spatial.metaCluster!="CD8.TREG" & rln$spatial.metaCluster!="Myeloid.Granulocytes" & rln$spatial.metaCluster!="HRS")
  plot_clustering_heatmap_wrapper(expr=rln[id,c(2:4,9,11:19,24,30,33,34)], 
  cell_clustering=rln$spatial.metaCluster[id], useMedians=TRUE,useQuantiles=FALSE,
color_clusters=color_clusters)
 #savePlot(file="RLN.allCase.expression.png")

```



### DLBCL spatial topology analysis
```{r, eval=FALSE}

  load("~/Documents/imageAnalysis/DLBCL/monirath/myData/revision-comments-11-6/survival-analysis-morphological-variants/PDL1-neighborhood-analysis/workingDir/re-phenotype/full.dn4.subType.corrected.mutation.tsne.CD20dim.filtered.RData")



 ### use the 5NN analysis approach.

 ## classify Tumor 5-NN to immune.  
 ## omit endo.
  ## use the synthetic immune/tumor classification. 
    full.dn4$compartment<-"immune" 
    full.dn4$compartment[which(full.dn4$subType.correction=="Tumor")]<-"Tumor" 
    full.dn4$compartment[which(full.dn4$subType.correction=="Endothelial")]<-"Endothelial"


   full.dn4.5nn2<-full.dn4
   full.dn4.5nn2$nndImmune.5nn<-0
   full.dn4.5nn2$nndTumor.5nn<-0
  full.dn4.5nn2$tumor.immune.5nn<-NA
  ## clusters distance neighbors for each ROI using k=40, and looks at 8-NN distances from tumor to immune
  for(roi in unique(full.dn4.5nn2$ROIID)){
  myroi<-subset(full.dn4.5nn2,full.dn4.5nn2$ROIID==roi)
   p<-phenographToPPP(case=myroi,marksCase=factor(myroi$compartment),shift=FALSE)
    myroi<-distanceClusterROI.5NN(synth=p,zz=myroi)
    full.dn4.5nn2$tumor.immune.5nn[match(myroi$uniqueLabel,full.dn4.5nn2$uniqueLabel)]<-myroi$tumor.immune.5nn
   full.dn4.5nn2$nndImmune.5nn[match(myroi$uniqueLabel,full.dn4$uniqueLabel)]<-myroi$nndImmune.5nn
  full.dn4.5nn2$nndTumor.5nn[match(myroi$uniqueLabel,full.dn4$uniqueLabel)]<-myroi$nndTumor.5nn
  }



  ErikMeta=full.dn4.5nn2[,
	c("nndImmune.5nn","nndTumor.5nn",
	"ROIID",
	"tumor.immune.5nn")] %>% group_by(ROIID,tumor.immune.5nn) %>% 
       dplyr::summarise_all(funs(mean)) %>%data.frame
     
          ##Levine used k=15 for meta.
     erikPheno<- Rphenograph(ErikMeta[,c("nndImmune.5nn","nndTumor.5nn")], k = 55)
     distance.meta.5nn.cluster<- factor(membership(erikPheno[[2]]))
     ErikMeta=cbind(ErikMeta,distance.meta.5nn.cluster)

   full.dn4.5nn2=left_join(full.dn4.5nn2, ErikMeta[,c("ROIID",
	"tumor.immune.5nn","distance.meta.5nn.cluster")], by = c("ROIID", "tumor.immune.5nn"))

  library(hrbrthemes)
 full.dn4.5nn2%>%group_by(ROIID,subType.correction,distance.meta.5nn.cluster)%>%summarise(immune=mean(nndImmune.5nn),tum=mean(nndTumor.5nn))%>%ggplot(aes(x=distance.meta.5nn.cluster,y=immune))+geom_boxplot()+facet_wrap(~subType.correction)+theme_ipsum(base_family="Arial")+ylab("Average distance to 5-NN immune cells (microns)")+xlab("distance meta cluster")
  
   ggsave("Tumor.immune.metacluster.5NN.png")

 ##assign letters to tumor.
  full.dn4.5nn2$tumor.5nn.class<-as.character(full.dn4.5nn2$subType.correction)
 full.dn4.5nn2$tumor.5nn.class[which(full.dn4.5nn2$tumor.5nn.class=="Tumor")]<-paste0("Tumor_",letters[full.dn4.5nn2$distance.meta.5nn.cluster[which(full.dn4.5nn2$subType.correction=='Tumor')]])

 ## add the unsupervised phenotypes.
 full.dn4.5nn2$tumor.5nn.class.unsup<-as.character(full.dn4.5nn2$unsup.subcommunity)
 full.dn4.5nn2$tumor.5nn.class.unsup[which(full.dn4.5nn2$subType.correction=="Tumor")]<-full.dn4.5nn2$tumor.5nn.class[which(full.dn4.5nn2$subType.correction=="Tumor")]

 color_clusters <- c("#DC050C", "#FB8072", "#1965B0", "#7BAFDE", "#882E72", 
  "#B17BA6", "#FF7F00", "#FDB462", "#E7298A", "#E78AC3", 
  "#33A02C", "#B2DF8A", "#55A1B1", "#8DD3C7", "#A6761D", 
  "#E6AB02", "#7570B3", "#BEAED4", "#666666", "#999999", 
  "#aa8282", "#d4b7b7", "#8600bf", "#ba5ce3", "#808000", 
  "#aeae5c", "#1e90ff", "#00bfff", "#56ff0d", "#ffff00")
    spatCol<-getSpatialPhenoColors(full.dn4.5nn2)


```



### Figure 5 B,C,D

```{r, eval=FALSE}
   absoluteTMEProportion<-function(full.dn4=NULL,tumorsToExclude=NULL,phenoType=NULL){
 ## the phenotype should be a column vector of "immune/tumor" only binary
 ###
   immune<-full.dn4[!full.dn4[,phenoType]%in%tumorsToExclude,]
   roiSum<-immune%>%group_by_("case",phenoType)%>%summarise(count=n())%>%mutate(freq=count/sum(count))%>%data.frame
  roiSum<-roiSum[which(roiSum[,2]=="immune"),]
   roiSum<-roiSum[order(roiSum$freq,decreasing=FALSE),]
    return(roiSum)
 }

   tme<-absoluteTMEProportion(full.dn4=full.dn4.5nn2,phenoType="immune.prop")
 roiSum<-full.dn4.5nn2[which(full.dn4.5nn2$subType.correction=="Tumor"),]%>%group_by(case,tumor.5nn.class)%>%summarise(count=n())%>%mutate(freq=count/sum(count))%>%data.frame

    ##must have the absolute ratio plot created.
    colnames(roiSum)<-c("case","Spatial.Class","count","proportion")
      roiSum$Spatial.Class<-factor(roiSum$Spatial.Class)
   roiSum$case<-factor(roiSum$case,levels=rev(as.character(tme$case)))
  cols<-getSpatialPhenoColors(full.dn4.5nn2)
  roiSum<-roiSum[which(roiSum$case!="Case_20"),]
  finalStack<-ggplot(roiSum,aes(y=proportion,x=case,fill=Spatial.Class))+geom_bar(stat='identity')+coord_flip()+scale_fill_manual(values=cols[match(levels(roiSum$Spatial.Class),cols$phenotype),"colors"])+theme_ipsum(base_family="Arial")
  ##FIGURE 5B
  print(finalStack)


 ## FIGURE 5C
   centroidSD<- full.dn4.5nn2[which(full.dn4.5nn2$subType.correction=="Tumor"),]%>%group_by(tumor.5nn.class.unsup)%>%summarise(nndImmune.5nn=sd(nndImmune.5nn))%>%data.frame()

 di<- full.dn4.5nn2[which(full.dn4.5nn2$subType.correction=="Tumor"),]%>%group_by(tumor.5nn.class.unsup)%>%summarise(nndImmune.5nn=mean(nndImmune.5nn))%>%data.frame()
   di[,1]<-factor(di[,1],levels=c(di[order(di[,2]),1]))
   cols[9,2]<-color_clusters[5]
  di%>%reshape2::melt()%>%ggplot(aes(x=tumor.5nn.class.unsup,y=value,fill=tumor.5nn.class.unsup))+geom_bar(stat='identity')+facet_wrap(~variable)+theme_ipsum(base_family="Arial")+theme(axis.text.x = element_text(angle = 90, hjust = 1))+scale_fill_manual(values=cols[match(levels(di[,1]),cols[,1]),"colors"])


    phenoColors<-getSpatialPhenoColors(full.dn4=full.dn4.5nn2)
 rownames(centroidSD)<-centroidSD$tumor.5nn.class.unsup
 sdPrim<-centroidSD[,-1]
  ## confidence interval. 95%
 sdPrim<- sdPrim/sqrt(33)
  error<- qt(0.975,df=9-1)*sdPrim
   di$lower<-di[,2]-error
   di$upper<-di[,2]+error
  
 

 
  ggplot(di,aes(x=tumor.5nn.class.unsup,y=nndImmune.5nn,fill=tumor.5nn.class.unsup))+geom_bar(stat='identity')+geom_errorbar(aes(ymin=lower,ymax=upper),width=0.5,alpha=0.5)+theme_ipsum(base_family="Arial")+theme(axis.text.x = element_text(angle = 45, hjust = 1))+scale_fill_manual(values=phenoColors[match(levels(di$tumor.5nn.class.unsup),phenoColors$phenotype),'colors'])+xlab("Tumor spatial cluster")+ylab("Average 5-NN distance (microns)")
 
 ggsave("~/Documents/imageAnalysis/DLBCL/simpleModel-1-14/Figure6-CD8-5NN-spatialModel-RICO/tumor.cd8.dlbcl/Figure6-final/Nearest.5NN.Immune.spatial.phenotype.distances.png")
 ####



 ## Figure 5D multivariate regression.
   absol.prop<-as.data.frame.matrix(table(full.dn4.5nn2$case,full.dn4.5nn2$tumor.5nn.class.unsup))
  absol.prop<-100*absol.prop/rowSums(absol.prop)
  absol.prop$HANS<-full.dn4.5nn2$COO[match(rownames(absol.prop),full.dn4.5nn2$case)]
 absol.prop$NGCB<-ifelse(absol.prop$HANS=="NGCB",1,0)
  absol.prop$IPI<-full.dn4.5nn2$IPI[match(rownames(absol.prop),full.dn4.5nn2$case)]
  absol.prop$immune<-tme$freq[match(rownames(absol.prop),tme$case)]

  spatCol<-getSpatialPhenoColors(full.dn4.5nn2)

  tum.lr<-glm(NGCB~Tumor_a+Tumor_b+Tumor_c+Tumor_d+Tumor_e+Tumor_f+Tumor_g+Tumor_h+Tumor_i+IPI,family='binomial',absol.prop)
  mlr.lr<-tum.lr%>%confint%>%data.frame
  mlr.lr$estimate<-coef(tum.lr)
   mlr.lr<-mlr.lr[order(mlr.lr$estimate),]
  mlr.lr<-mlr.lr[grepl("Tumor_",rownames(mlr.lr)),]
  mlr.lr$phenotype<-rownames(mlr.lr)
  mlr.lr$phenotype<-factor(mlr.lr$phenotype,levels=rownames(mlr.lr))

  ggplot(mlr.lr,aes(x=phenotype,y=estimate))+geom_point(size=4,aes(color=phenotype))+geom_errorbar(aes(ymin=X2.5..,ymax=X97.5..),width=0.2,color='grey39')+scale_color_manual(values=spatCol$colors[match(levels(mlr.lr$phenotype),spatCol$phenotype)])+theme_ipsum(base_family='Arial')+theme(axis.text.x = element_text(angle = 90, hjust = 1))+xlab("Spatial phenotype")+ylab("Non-GC log-odds (IPI adjusted)")+ggtitle("Spatial Phenotype Non-GC association")
 
ggsave("~/Documents/imageAnalysis/DLBCL/simpleModel-1-14/Figure6-CD8-5NN-spatialModel-RICO/tumor.cd8.dlbcl/Tumor-analysis-5NN/mult.LR.IPI.adjusted.spatial.png")


```

### Compare multivariate logistic AIC to random
```{r, eval=FALSE}
## random network comparison.
 ## we want to compare the HANS MLR to observed domain.
  mlr<-compareRandomNetwork(full.dn4=full.dn4.5nn2,N=250,myFormula=formula("NGCB~Tumor_c+Tumor_d+Tumor_e+Tumor_g+Tumor_h+Tumor_i+IPI"))

  AIC<-c(sapply(mlr,function(x) x$aic))
 ###using the best model.
  p<-1-length(which(AIC>hans.mlr2$aic))/(1+length(AIC))
   data.frame(AIC=AIC)%>%ggplot(aes(x=AIC))+geom_density(fill='lightblue')+theme_ipsum(base_family="Arial")+geom_vline(xintercept=hans.mlr2$aic,col='red',linetype='dashed')+xlab("AIC random network (N=250)")+ylab("Density of randomized network")+ggplot2::annotate('text',x=46,y=0.041,label=paste0("p=",round(p,3)))
 ##write to notebook.
   ggsave("~/Documents/imageAnalysis/DLBCL/simpleModel-1-14/Figure6-CD8-5NN-spatialModel-RICO/tumor.cd8.dlbcl/Tumor-analysis-5NN/AIC.random.vs.best.tumorTopography.png")

   addWorksheet(fig5,"AIC.logistic")
   writeData(fig5,"AIC.logistic",
	data.frame(random=AIC,oberved=hans.mlr2$aic,tumor.subCluster=sub.mlr$aic),
	rowNames=TRUE,withFilter=FALSE,colNames=TRUE,startCol=1,startRow=1)
  saveWorkbook(fig5,file="~/Documents/imageAnalysis/DLBCL/simpleModel-1-14/Figure6-CD8-5NN-spatialModel-RICO/tumor.cd8.dlbcl/Tumor-analysis-5NN/Figure5Table.xlsx",overwrite=TRUE)


```

### Spatial organization model.


```{r,eval}


  HH3<-NULL
   rois<-unique(full.dn4.5nn2$ROIID)
  for(i in rois){
  print(i)
  data<-subset(full.dn4.5nn2,full.dn4.5nn2$ROIID==i)
     pp<-phenographToPPP(case=data,marksCase=factor(data$tumor.5nn.class.unsup),shift=FALSE)
   H<-hyperframe(point=pp,
	response=unique(data$response),
	ROI=i)
   if(is.null(HH3)!=TRUE){
  HH3<-rbind(H,HH3)
  }else{
 HH3<-H
  } 
 } ###

 HH3$COO<-full.dn4.5nn2$COO[match(HH3$ROI,full.dn4.5nn2$ROIID)]

 table(full.dn4.5nn2$tumor.5nn.class[which(full.dn4.5nn2$subType.correction=="Tumor")])%>%prop.table
  mantle<-HH3

 ## perform Clark-Evans index on lymph node.
  ## use the clark evans spatial test to a normal lymph-node.
 load("~/Documents/imageAnalysis/DLBCL/monirath/myData/revision-comments-11-6/survival-analysis-morphological-variants/PDL1-neighborhood-analysis/workingDir/steidl-lymphode-classification/steidl-RLN-classification-analysis-Case4-1-23/rln.dn4.nbhd.5nn.1-23.RData")

   table(rln.nbhd.5nn$primary.phenotype)
    ## 
   rln.nbhd.5nn$case%>%table
  
   rln<-NULL
  rois<-c("Case1_6" , "Case2_7",  "Case3_8" , "Case4_9",  "Case5_10")
  for(i in rois){
  print(i)
  data<-subset(rln.nbhd.5nn,rln.nbhd.5nn$ROIID==i)
  data<-data[which(data$primary.phenotype=='BCell'),]
     pp<-phenographToPPP(case=data,marksCase=factor(data$primary.phenotype),shift=FALSE)
   H<-hyperframe(point=pp,
	#response=unique(data$response),
	#COO=unique(data$COO),
	ROI=i)
   if(is.null(rln)!=TRUE){
  rln<-rbind(H,rln)
  }else{
 rln<-H
  } 
 } ###

  rln$z<-with(rln,clarkevans.test(point,alternative='clustered',correction='Donnelly')$statistic)
  



 ##drop a (<1%) and b (<10%) due to rarity.
  ## drop e and h because they are associated with COO.
 man4<-with(HH3, point[which(marks(point)%in%unique(c(
	'Tumor_c',
	'Tumor_d',
	'Tumor_f',
	'Tumor_g',
	'Tumor_i')))])
   names(man4)<-mantle$ROI
  id<-which(sapply(man4,npoints)!=0)
  man4<-hyperframe(point=man4[id],ROI=names(man4)[id])
  man4$COO<-mantle$COO[match(man4$ROI,mantle$ROI)]
 ## border corrections on Clark-Evans statistic.
  man4$z<-with(man4,clarkevans.test(point,alternative='clustered',correction='Donnelly')$statistic)
 
 ## perform regression.
 ### using full topology, good model.
  cedata2<-data.frame(COO=man4$COO,z=man4$z,row.names=man4$ROI)
  print( lm(z~COO,cedata2)%>%summary)
  

 ## drop tumor_d core to identify best model.
 man3<-with(HH3, point[which(marks(point)%in%unique(c(
	'Tumor_c',
	'Tumor_i',
	'Tumor_f',
	'Tumor_g')))])
   names(man3)<-mantle$ROI
   id<-which(sapply(man3,npoints)!=0)
  man3<-hyperframe(point=man3[id],ROI=names(man3)[id])
  man3$COO<-mantle$COO[match(man3$ROI,mantle$ROI)]
 ## border corrections on Clark-Evans statistic.
  man3$z<-with(man3,clarkevans.test(point,alternative='clustered',correction='Donnelly')$statistic)


 ## perform regression.
  cedata<-data.frame(COO=man3$COO,z=man3$z,row.names=man3$ROI)
  cedata$case<-full.dn4.5nn2$case[match(rownames(cedata),full.dn4.5nn2$ROIID)]
  cedata$case<-factor(cedata$case)
  ### mixed effects model. 
  ##droppin tumor_d, much improved.
  print( lm(z~COO,cedata)%>%summary)
    fit<-lm(z~COO,cedata)%>%summary


 ## RLN clark evans.
   rlnZ<-data.frame(COO="RLN",z=rln$z,case=rln$ROI)


  ce.d<-rbind(cedata,rlnZ)
  ce.d$COO<-relevel(ce.d$COO,ref='RLN')

  
 ## more conservative results with case mixed effects model.


   clarkEvans.fit<-aov(z~COO,ce.d)
  clarkEvans.fit%>%TukeyHSD
	library(rstatix)
   stat.test<-  clarkEvans.fit%>%tukey_hsd()

 ce.d$COO <- as.factor(ce.d$COO)
 library(ggpubr)
  ggboxplot(ce.d, x = "COO", y = "z",fill='COO') +
  stat_pvalue_manual(
    stat.test, label = "p.adj", 
    y.position = c(1.8, 1.6, 1.4)
 )+ylab("Clark-evans test statistic")+scale_fill_manual(values=c('khaki2','red','royalblue2'))+xlab("HANS classification")+ggtitle("Spatial clustering of tumor topography")

    ggsave("~/Documents/imageAnalysis/DLBCL/simpleModel-1-14/Figure6-CD8-5NN-spatialModel-RICO/tumor.cd8.dlbcl/Tumor-analysis-5NN/evans.statistic.HANS.2.png")
  
full.dn4.5nn2$evansZ.cifg<-man3$z[match(full.dn4.5nn2$ROIID,man3$ROI)]

 
```


### Associations of the labeled phenotypes and the spatial domains.
```{r, eval=FALSE}

  ## construct the manual cutting for the DLBCL population.
load(file="~/Documents/imageAnalysis/DLBCL/monirath/myData/revision-comments-11-6/survival-analysis-morphological-variants/PDL1-neighborhood-analysis/workingDir/re-phenotype/full.dn4.subType.corrected.mutation.tsne.CD20dim.appended.un.filtered.RData")
 
 x<-table(full.dn4$tumor.5nn.umap.relabel,full.dn4$annotated.umap.simple)%>%as.data.frame.matrix

  library(dplyr) 
  zz<- zScorePatientExpression(full.dn4=full.dn4,markers=c(1:31,104:111),ROIID.column=32)

    subExpr<-zz%>%group_by(tumor.5nn.umap.relabel)%>%summarise(CCR4=mean(Cell_CCR4),PD1=mean(Cell_PD1),CCR4.SD=sd(Cell_CCR4),
	PD1.SD=sd(Cell_PD1))%>%data.frame


```
